// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNBLnWhiTmnAheiv4Xzbd8V_AKx0hdW0o',
    appId: '1:204399458840:web:2efe29be0cd57c1f67216d',
    messagingSenderId: '204399458840',
    projectId: 'nextech-mobile',
    authDomain: 'nextech-mobile.firebaseapp.com',
    storageBucket: 'nextech-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7850BU4Ww5tF5iKW__ME5BMHnKXSNAmc',
    appId: '1:204399458840:android:c8ecc5b79e7e7c1c67216d',
    messagingSenderId: '204399458840',
    projectId: 'nextech-mobile',
    storageBucket: 'nextech-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkTfernO62pGuMVSUe20P1GbBsHV9aOs',
    appId: '1:204399458840:ios:bd12a06e040fff3f67216d',
    messagingSenderId: '204399458840',
    projectId: 'nextech-mobile',
    storageBucket: 'nextech-mobile.firebasestorage.app',
    iosBundleId: 'com.example.nextechMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkTfernO62pGuMVSUe20P1GbBsHV9aOs',
    appId: '1:204399458840:ios:bd12a06e040fff3f67216d',
    messagingSenderId: '204399458840',
    projectId: 'nextech-mobile',
    storageBucket: 'nextech-mobile.firebasestorage.app',
    iosBundleId: 'com.example.nextechMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNBLnWhiTmnAheiv4Xzbd8V_AKx0hdW0o',
    appId: '1:204399458840:web:d0d2ace312ea18bf67216d',
    messagingSenderId: '204399458840',
    projectId: 'nextech-mobile',
    authDomain: 'nextech-mobile.firebaseapp.com',
    storageBucket: 'nextech-mobile.firebasestorage.app',
  );
}
